accepted = ["Apache-2.0", "ISC", "MIT", "MPL-2.0"]
ignore-dev-dependencies = true
private = { ignore = true }
workarounds = [
    "ring"
]

[ring]
accepted = ["OpenSSL"]

[alloc-stdlib]
accepted = ["BSD-3-Clause"]

[alloc-no-stdlib]
accepted = ["BSD-3-Clause"]

[encoding_rs]
accepted = ["BSD-3-Clause"]

[Inflector]
accepted = ["BSD-2-Clause"]

[instant]
accepted = ["BSD-3-Clause"]

[subtle]
accepted = ["BSD-3-Clause"]

[unicode-ident]
accepted = ["Unicode-DFS-2016"]

[webpki.clarify]
license = "ISC"

[[webpki.clarify.files]]
path = 'LICENSE'
license = 'ISC'
checksum = '5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a'
