[graph]
targets = [
    "aarch64-unknown-linux-musl",
    "arm-unknown-linux-musleabihf",
    "armv7-unknown-linux-musleabihf",
    "x86_64-unknown-linux-musl",
    "i686-unknown-linux-musl",
    "x86_64-pc-windows-gnu",
]
all-features = true


[advisories]
version = 2
ignore = ["RUSTSEC-2023-0071"]

[bans]
multiple-versions = "allow"
wildcards = 'deny'

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
    "https://github.com/utkarshkukreti/markup.rs",
]

[licenses]
confidence-threshold = 0.9
allow = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "ISC",
    "Unicode-3.0",
]
exceptions = [
    { allow = ["BSD-3-Clause"], crate = "Inflector" },
    { allow = ["BSD-3-Clause"], crate = "alloc-no-stdlib" },
    { allow = ["BSD-3-Clause"], crate = "alloc-stdlib" },
    { allow = ["BSD-3-Clause"], crate = "encoding_rs" },
    { allow = ["BSD-3-Clause"], crate = "instant" },
    { allow = ["BSD-3-Clause"], crate = "subtle" },
    { allow = ["OpenSSL"], crate = "ring" },
    { allow = ["Zlib"], crate = "foldhash" },
]

[[licenses.clarify]]
crate = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
crate = "webpki"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]

[[licenses.clarify]]
crate = "rustls-webpki"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]
