version: 2
updates:
  - package-ecosystem: "cargo"
    assignees:
      - friedemannsommer
    directory: "/"
    reviewers:
      - friedemannsommer
    schedule:
      day: friday
      interval: weekly
      timezone: "Etc/UTC"

  - package-ecosystem: "github-actions"
    assignees:
      - friedemannsommer
    directory: "/"
    reviewers:
      - friedemannsommer
    schedule:
      day: friday
      interval: weekly
      timezone: "Etc/UTC"
