[package]
name = "email-view-tracker"
version = "0.1.1"
edition = "2021"
license = "AGPL-3.0"
publish = false

[profile.release]
codegen-units = 1
lto = true

[workspace]
members = [
    ".",
    "entity",
    "migration"
]

[dependencies]
actix-identity = "=0.5.2"
entity = { path = "entity" }
fern = "=0.6.1"
getrandom = "=0.2.8"
hex = "=0.4.3"
log = "=0.4.17"
markup = "=0.13.1"
migration = { path = "migration" }
once_cell = "=1.16.0"
serde = "=1.0.150"
thiserror = "=1.0.38"
url = "=2.3.1"

[dependencies.actix-web]
version = "=4.2.1"
default-features = false
features = ["compress-brotli", "compress-gzip", "compress-zstd", "macros"]

[dependencies.actix-session]
version = "=0.7.2"
features = ["cookie-session"]

[dependencies.clap]
version = "=4.0.32"
default-features = false
features = ["std", "color", "help", "usage", "error-context", "suggestions", "derive", "env", "cargo"]

[dependencies.uuid]
version = "=1.2.2"
default-features = false
features = ["v4"]

[dependencies.sea-orm]
version = "=0.10.6"
default-features = false
features = ["sqlx-mysql", "sqlx-postgres", "runtime-actix-rustls"]

[dependencies.argon2]
version = "=0.4.1"
default-features = false
features = ["std", "password-hash", "parallel"]

[dependencies.moka]
version = "=0.9.6"
default-features = false
features = ["atomic64", "dash"]

[dependencies.time]
version = "=0.3.17"
default-features = false
features = ["std"]

[build-dependencies]
lightningcss = "=1.0.0-alpha.38"
