[package]
name = "email-view-tracker"
version = "0.1.18"
edition = "2021"
license = "AGPL-3.0"
publish = false

[profile.release]
codegen-units = 1
lto = true

[workspace]
members = [
    ".",
    "entity",
    "migration"
]

[dependencies]
actix-identity = "=0.7.1"
entity = { path = "entity" }
fern = "=0.6.2"
getrandom = "=0.2.14"
hex = "=0.4.3"
log = "=0.4.21"
markup = { git = "https://github.com/utkarshkukreti/markup.rs", rev = "c1dc693e0d3e312d52160c312961bf47f1cffbf7" }
migration = { path = "migration" }
once_cell = "=1.19.0"
serde = "=1.0.197"
thiserror = "=1.0.58"
time = "=0.3.36"
url = "=2.5.0"

[dependencies.actix-web]
version = "=4.5.1"
default-features = false
features = ["compress-brotli", "compress-gzip", "compress-zstd", "macros"]

[dependencies.actix-session]
version = "=0.9.0"
features = ["cookie-session"]

[dependencies.clap]
version = "=4.5.4"
default-features = false
features = ["std", "color", "help", "usage", "error-context", "suggestions", "derive", "env", "cargo"]

[dependencies.uuid]
version = "=1.8.0"
default-features = false
features = ["v4"]

[dependencies.sea-orm]
version = "=0.12.15"
default-features = false
features = ["sqlx-mysql", "sqlx-postgres", "runtime-actix-rustls"]

[dependencies.argon2]
version = "=0.5.3"
default-features = false
features = ["std", "password-hash"]

[dependencies.mini-moka]
version = "=0.10.3"
default-features = false
features = ["sync"]

[build-dependencies]
lightningcss = "=1.0.0-alpha.55"
proc-macro2 = "=1.0.79"
quote = "=1.0.36"
time = { version = "=0.3.36", features = ["macros", "formatting"] }
