[package]
name = "email-view-tracker"
version = "0.1.14"
edition = "2021"
license = "AGPL-3.0"
publish = false

[profile.release]
codegen-units = 1
lto = true

[workspace]
members = [
    ".",
    "entity",
    "migration"
]

[dependencies]
actix-identity = "=0.6.0"
entity = { path = "entity" }
fern = "=0.6.2"
getrandom = "=0.2.11"
hex = "=0.4.3"
log = "=0.4.20"
markup = "=0.13.1"
migration = { path = "migration" }
once_cell = "=1.18.0"
serde = "=1.0.192"
thiserror = "=1.0.50"
time = "=0.3.30"
url = "=2.4.1"

[dependencies.actix-web]
version = "=4.4.0"
default-features = false
features = ["compress-brotli", "compress-gzip", "compress-zstd", "macros"]

[dependencies.actix-session]
version = "=0.8.0"
features = ["cookie-session"]

[dependencies.clap]
version = "=4.4.7"
default-features = false
features = ["std", "color", "help", "usage", "error-context", "suggestions", "derive", "env", "cargo"]

[dependencies.uuid]
version = "=1.5.0"
default-features = false
features = ["v4"]

[dependencies.sea-orm]
version = "=0.12.7"
default-features = false
features = ["sqlx-mysql", "sqlx-postgres", "runtime-actix-rustls"]

[dependencies.argon2]
version = "=0.5.2"
default-features = false
features = ["std", "password-hash"]

[dependencies.mini-moka]
version = "=0.10.2"
default-features = false
features = ["sync"]

[build-dependencies]
lightningcss = "=1.0.0-alpha.51"
proc-macro2 = "=1.0.69"
quote = "=1.0.33"
time = { version = "=0.3.30", features = ["macros", "formatting"] }
