[package]
name = "email-view-tracker"
version = "0.1.5"
edition = "2021"
license = "AGPL-3.0"
publish = false

[profile.release]
codegen-units = 1
lto = true

[workspace]
members = [
    ".",
    "entity",
    "migration"
]

[dependencies]
actix-identity = "=0.5.2"
entity = { path = "entity" }
fern = "=0.6.1"
getrandom = "=0.2.8"
hex = "=0.4.3"
log = "=0.4.17"
markup = "=0.13.1"
migration = { path = "migration" }
once_cell = "=1.17.0"
serde = "=1.0.152"
thiserror = "=1.0.38"
url = "=2.3.1"

[dependencies.actix-web]
version = "=4.3.0"
default-features = false
features = ["compress-brotli", "compress-gzip", "compress-zstd", "macros"]

[dependencies.actix-session]
version = "=0.7.2"
features = ["cookie-session"]

[dependencies.clap]
version = "=4.1.4"
default-features = false
features = ["std", "color", "help", "usage", "error-context", "suggestions", "derive", "env", "cargo"]

[dependencies.uuid]
version = "=1.3.0"
default-features = false
features = ["v4"]

[dependencies.sea-orm]
version = "=0.11.0"
default-features = false
features = ["sqlx-mysql", "sqlx-postgres", "runtime-actix-rustls"]

[dependencies.argon2]
version = "=0.4.1"
default-features = false
features = ["std", "password-hash", "parallel"]

[dependencies.mini-moka]
version = "=0.10.0"
default-features = false
features = ["sync"]

[dependencies.time]
version = "=0.3.19"
default-features = false
features = ["std", "macros"]

[build-dependencies]
lightningcss = "=1.0.0-alpha.39"
proc-macro2 = "=1.0.51"
quote = "=1.0.23"
time = "=0.3.19"
