[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
]
all-features = true

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = []

[licenses]
unused-allowed-license = "warn"
allow = [
    "MIT",
    "Apache-2.0",
    "MPL-2.0"
]
# [between 0.0 and 1.0].
confidence-threshold = 0.8
exceptions = [
    { name = "encoding_rs", allow = ["BSD-3-Clause"] },
    { name = "ring", allow = ["LicenseRef-ring"] },
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[licenses.private]
ignore = true
registries = []

[bans]
multiple-versions = "warn"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/utkarshkukreti/markup.rs"]
