version: "3.9"
services:
  mysql:
    image: mariadb:10.10-jammy
    ports:
      - "3310:3306"
    environment:
      MARIADB_DATABASE: email_view_tracker
      MARIADB_ROOT_PASSWORD: local
  postgres:
    image: postgres:15-alpine
    ports:
      - "3311:5432"
    environment:
      POSTGRES_DB: email_view_tracker
      POSTGRES_PASSWORD: local
